# Generated by Django 4.2.1 on 2023-06-01 22:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0003_alter_room_options_room_members"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="message",
            options={"ordering": ["-sent"]},
        ),
        migrations.AddField(
            model_name="language",
            name="alpha_2",
            field=models.CharField(default="PL", max_length=2),
        ),
    ]
